classDiagram
    class Student {
        - String studentId
        - String name
        - int age
        - String major
        + Student(String, String, int, String)
        + getStudentId() String
        + getName() String
        + setName(String) void
        + getAge() int
        + setAge(int) void
        + getMajor() String
        + setMajor(String) void
        + getStudentInfo() String
    }
