classDiagram
    class Product {
        - String productId
        - String name
        - double price
        + Product(String, String, double)
        + getProductId() String
        + getName() String
        + setName(String) void
        + getPrice() double
        + setPrice(double) void
        + getProductInfo() String
    }
